services:
  # Backend Service Configuration
  - type: web
    name: community-backend
    env: node
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: MONGO_URI
        value: <YOUR_MONGO_DB_CONNECTION_STRING>
      - key: JWT_SECRET
        value: <YOUR_JWT_SECRET>
    autoDeploy: true

  # Frontend Service Configuration
  - type: web
    name: community-frontend
    env: node
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l ${PORT}
    envVars:
      - key: REACT_APP_API_URL
        value: https://community-backend.onrender.com
    autoDeploy: true
